Library/Models/Librarian.cs
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;

namespace Library.Models
{
    public class Librarian
    {
        public int LibrarianId { get; set; }
        public bool IsHidden { get; set; }
        public string? LibrarainCode { get; set; }
        [Required(ErrorMessage ="Please Enter Your Name")]
        public string? LibrarianName { get; set; }
        public string? Sex { get; set; }

        [BindProperty(SupportsGet = true), DataType(DataType.Date)]
        public DateTime Dob {  get; set; }
        public string? Pob { get; set; }

        [Required(ErrorMessage ="Phone Number Is Required")]
        public string? Phone {  get; set; }

        public ICollection<Borrow>? Borrow { get; set; }
    }
}

Library/Controllers/LibrarianController.cs
using Library.Models;
using Library.Services;
using Microsoft.AspNetCore.Mvc;

namespace Library.Controllers
{
    public class LibrarianController : Controller
    {
        private readonly ILibrarianService _service;
        public LibrarianController(ILibrarianService service)
        {
            _service = service;
        }
		public IActionResult Index()
        {
            var librarian = _service.GetAll();
            return View("Index", librarian);

        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Store(Librarian librarian)
        {
            if (!ModelState.IsValid)
            {
                return View("Create",librarian);
            }
            var result = _service.Create(librarian);
            if (result)
            {
                return RedirectToAction("Index");
            }
             return View("Create",librarian);
        }

        [HttpGet]
        public  IActionResult Edit(int LibrarianId)
        { 
            var li = _service.Get(LibrarianId);
            return View("Edit", li);
        }

        [HttpPost]
        public IActionResult Update(Librarian librarian)
        {
            if (!ModelState.IsValid)
            {
                return View("Edit", librarian); 
            }
            var result = _service.Update(librarian);
            if (result)
            {
                return RedirectToAction("Index");
            }

            return View("Edit", librarian);
        }

        [HttpGet]
        public IActionResult Delete(int LibrarianId)
        {
            var li = _service.Get(LibrarianId);
            return View("Delete", li);
        }
        [HttpPost]
        public IActionResult Destroy(int LibrarianId)
        {
            if (!ModelState.IsValid)
            {
                return View("Delete", LibrarianId);
            }
            var result = _service.Delete(LibrarianId);
            if (result)
            {
                return RedirectToAction("Index");
            }
            return View("Delete",LibrarianId);
        }
    }
}

Library/Views/Librarian/Create.cshtml
@model Library.Models.Librarian
@{
    ViewData["Title"] = "Add New Librarain";
}

<div class="card">
    <div class="card-header">
        <h4 class="title float-left">Add Librarain</h4>
    </div>
    <div class="card-body">
        <form asp-action="Store" asp-controller="Librarian" method="post">
            <div class="row">
                <div class="form-group col-sm-6">
                    <label asp-for="LibrarianName" class="control-label">Librarian Name</label>
                    <input type="text" placeholder="LibrarianName" asp-for="LibrarianName" class="form-control" />
                </div>
                <div class="form-group col-sm-6">
                    <label asp-for="LibrarainCode" class="control-label">Librarain Code</label>
                    <input type="text" placeholder="LibrarainCode" asp-for="LibrarainCode" class="form-control" />
                </div>

            </div>
            <div class="row">
                <div class="form-group col-sm-6">
                    <label asp-for="Pob" class="control-label">POB</label>
                    <input type="text" placeholder="POB" asp-for="Pob" class="form-control" />
                </div>
                <div class="form-group col-sm-6">
                    <label asp-for="Sex" class="control-label">Sex</label>
                    <select class="custom-select" asp-for="Sex">
                        <option>Please Select Your Sex</option>

                        <option value="M">M</option>
                        <option value="F">F</option>
                    </select>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-sm-6">
                    <label asp-for="Dob" class="control-label">DOB</label>
                    <input type="date" placeholder="DOB" asp-for="Dob" class="form-control" />
                </div>
                <div class="form-group col-sm-6">
                    <label asp-for="Phone" class="control-label">Phone</label>
                    <input type="tel" placeholder="Phone Number" asp-for="Phone" class="form-control" />
                </div>
            </div>
            <div class="form-group form-check">
                <input class="form-check-input" type="checkbox" asp-for="IsHidden" />
                <label class="form-check-label ml-1">IsHidden</label>
               
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-success btn-sm float-lg-right ml-2">Add New Librarain</button>
                <a asp-action="Index" class="btn btn-danger btn-sm float-lg-right">Cancel</a>
            </div>
        </form>
    </div>
</div>

Library/Views/Librarian/Delete.cshtml
@model Library.Models.Librarian
@{
    ViewData["Title"] = "Delete Librarain";
}

<div class="card">
    <div class="card-header">
        <h4 class="title float-left">Librarain</h4>
    </div>
    <div class="card-body">
        <form asp-action="Destroy" asp-controller="Librarian" method="post">
            <input asp-for="LibrarianId" type="hidden" />
            <div class="row">
                <div class="form-group col-sm-6">
                    <label asp-for="LibrarianName" class="control-label">Librarain Name</label>
                    <input type="text" placeholder="LibrarainName" asp-for="LibrarianName" class="form-control" />
                </div>
                <div class="form-group col-sm-6">
                    <label asp-for="LibrarainCode" class="control-label">Librarain Code</label>
                    <input type="text" placeholder="LibrarainCode" asp-for="LibrarainCode" class="form-control" />
                </div>

            </div>
            <div class="row">
                <div class="form-group col-sm-6">
                    <label asp-for="Pob" class="control-label">POB</label>
                    <input type="text" placeholder="POB" asp-for="Pob" class="form-control" />
                </div>
                <div class="form-group col-sm-6">
                    <label asp-for="Sex" class="control-label">Sex</label>
                    <select class="custom-select" asp-for="Sex">
                        <option>Please Select Your Sex</option>

                        <option value="M">M</option>
                        <option value="F">F</option>
                    </select>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-sm-6">
                    <label asp-for="Dob" class="control-label">DOB</label>
                    <input type="date" placeholder="DOB" asp-for="Dob" class="form-control" />
                </div>
                <div class="form-group col-sm-6">
                    <label asp-for="Phone" class="control-label">Phone</label>
                    <input type="tel" placeholder="Phone Number" asp-for="Phone" class="form-control" />
                </div>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsHidden" /> @Html.DisplayNameFor(model => model.IsHidden)
                </label>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-success btn-sm float-lg-right ml-2">Delete</button>
                <a asp-action="Index" class="btn btn-danger btn-sm float-lg-right">Cancel</a>
            </div>
        </form>
    </div>
</div>

Library/Views/Librarian/Edit.cshtml
@model Library.Models.Librarian
@{
    ViewData["Title"] = "Update Librarain";
}

<div class="card">
    <div class="card-header">
        <h4 class="title float-left">Librarain</h4>
    </div>
    <div class="card-body">
        <form asp-action="Update" asp-controller="Librarian" method="post">

            <input asp-for="LibrarianId" type="hidden" />
            <div class="row">
                <div class="form-group col-sm-6">
                    <label asp-for="LibrarianName" class="control-label">Librarain Name</label>
                    <input type="text" placeholder="LibrarainName" asp-for="LibrarianName" class="form-control" />
                </div>
                <div class="form-group col-sm-6">
                    <label asp-for="LibrarainCode" class="control-label">Librarain Code</label>
                    <input type="text" placeholder="LibrarainCode" asp-for="LibrarainCode" class="form-control" />
                </div>

            </div>
            <div class="row">
                <div class="form-group col-sm-6">
                    <label asp-for="Pob" class="control-label">POB</label>
                    <input type="text" placeholder="POB" asp-for="Pob" class="form-control" />
                </div>
                <div class="form-group col-sm-6">
                    <label asp-for="Sex" class="control-label">Sex</label>
                    <select class="custom-select" asp-for="Sex">
                        <option>Please Select Your Sex</option>

                        <option value="M">M</option>
                        <option value="F">F</option>
                    </select>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-sm-6">
                    <label asp-for="Dob" class="control-label">DOB</label>
                    <input type="date" placeholder="DOB" asp-for="Dob" class="form-control" />
                </div>
                <div class="form-group col-sm-6">
                    <label asp-for="Phone" class="control-label">Phone</label>
                    <input type="tel" placeholder="Phone Number" asp-for="Phone" class="form-control" />
                </div>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsHidden" /> @Html.DisplayNameFor(model => model.IsHidden)
                </label>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-success btn-sm float-lg-right ml-2">Update</button>
                <a asp-action="Index" class="btn btn-danger btn-sm float-lg-right">Cancel</a>
            </div>
        </form>
    </div>
</div>

Library/Views/Librarian/Index.cshtml
@model IEnumerable<Library.Models.Librarian>

@{
    ViewData["Title"] = "Librarian";
}
<div class="card">
    <div class="card-header">
        <h4 class="title float-left">All Librarian</h4>
    </div>
    <div class="card-body">
        <p>
            <a asp-action="Create" class="btn btn-success btn-sm float-right">Add New Librarian</a>
        </p>
        <table class="table table-responsive table-condensed">
            <thead>
                <tr>
                    <th class="fst-italic">
                        @Html.DisplayNameFor(model => model.LibrarianId)
                    </th>
                    <th class="fst-italic">
                        @Html.DisplayNameFor(model => model.LibrarianName)
                    </th>
                    <th class="fst-italic">
                        @Html.DisplayNameFor(model => model.LibrarainCode)
                    </th>
                    <th class="fst-italic">
                        @Html.DisplayNameFor(model => model.Sex)
                    </th>
                    <th class="fst-italic">
                        @Html.DisplayNameFor(model => model.Dob)
                    </th>
                    <th class="fst-italic">
                        @Html.DisplayNameFor(model => model.Pob)
                    </th>
                    <th class="fst-italic">
                        @Html.DisplayNameFor(model => model.Phone)
                    </th>
                    <th class="fst-italic">
                        @Html.DisplayNameFor(model => model.IsHidden)
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(model => item.LibrarianId)
                        </td>
                        <td>
                            @Html.DisplayFor(model => item.LibrarianName)
                        </td>
                        <td>
                            @Html.DisplayFor(model => item.LibrarainCode)
                        </td>
                        <td>
                            @Html.DisplayFor(model => item.Sex)
                        </td>
                        <td>
                            @Html.DisplayFor(model => item.Dob)
                        </td>
                        <td>
                            @Html.DisplayFor(model => item.Pob)
                        </td>
                        <td>
                            @Html.DisplayFor(model => item.Phone)
                        </td>
                        <td>
                            @Html.DisplayFor(model => item.IsHidden)
                        </td>
                        <td>
                            <a asp-controller="Librarian" asp-action="Edit" asp-route-LibrarianId="@item.LibrarianId" class="btn btn-sm btn-success">Edit</a>
                            <a asp-controller="Librarian" asp-action="Delete" asp-route-LibrarianId="@item.LibrarianId" class="btn btn-sm btn-danger"> Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>