Library/Models/Borrow.cs
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Library.Models
{
    public class Borrow
    {
        public int BorrowId { get; set; }

        public bool IsHidden { get; set; }

        [ForeignKey(nameof(Customer))]
        public int CustomerId { get; set; }

        [ForeignKey(nameof(Librarian))]
        public int LibrarianId { get; set; }

        [BindProperty(SupportsGet = true), DataType(DataType.Date)]
        public DateTime? BorrowDate { get; set; }
        public string? BorrowCode { get; set; }

        
        public decimal? Depositamount { get; set; }

        [BindProperty(SupportsGet = true), DataType(DataType.Date)]
        public DateTime? Duedate { get; set; }
        public decimal? FineAmount { get; set; }
        public string? Memo {  get; set; }

        public Customer? Customer { get; set; }

        public Librarian? Librarian { get; set; }
    }
}

Library/Controllers/BorrowController.cs
using Library.Models;
using Library.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Library.Controllers
{
    public class BorrowController : Controller
    {
        private readonly IBorrowService _service;
        private readonly ICustomerService _cus;
        private readonly ILibrarianService _lia;
        private readonly IBorrowDetailService _borrowdetail;
        private readonly IBookService _book;
        private readonly ICatalogService _catalog;
        public BorrowController(IBorrowService service, ICustomerService cus, ILibrarianService lia, IBorrowDetailService borrowdetail, IBookService book, ICatalogService catalog)
        {
            _service = service;
            _cus = cus;
            _lia = lia;
            _borrowdetail = borrowdetail;
            _book = book;
            _catalog = catalog;
        }

        public IActionResult Index(int? page)
        {
           
            var borrow = _service.GetAll();
            return View("Index", borrow);
        }

       

        [HttpGet]
        public IActionResult Create()
        {
            var customer = _cus.GetAll();
            ViewBag.Customer = new SelectList(customer, "CustomerId", "CustomerName");
            //---------------------------------------------------------------------//

            var librarian = _lia.GetAll();
            ViewBag.librarians = new SelectList(librarian, "LibrarianId", "LibrarianName");

            var book = _book.GetAll();
            ViewBag.Book = new SelectList(book, "BookId", "Catalog.CatalogName");
            //-------------------------------------------------------------------------//
           


            return View("Create");
        }
        [HttpPost]
        public IActionResult Store(Borrow borrow, BorrowDetail borrowDetail)
        {
            if (!ModelState.IsValid)
            {
                return View("Create");
            }
            var result = _service.Create(borrow, borrowDetail);
            if (result)
            {
               return RedirectToAction("Index", "BorrowDetial");
            }
            return View("Create");
        }

        [HttpGet]
        public IActionResult Edit(int BorrowId, int BorrowDetailId)
        {
            var customer = _cus.GetAll();
            ViewBag.Customer = new SelectList(customer, "CustomerId", "CustomerName");
            //---------------------------------------------------------------------//

            var librarian = _lia.GetAll();
            ViewBag.librarians = new SelectList(librarian, "LibrarianId", "LibrarianName");

            //-------------------------------------------------------------------------//
            var book = _book.GetAll();
            ViewBag.Book = new SelectList(book, "BookId", "Catalog.CatalogName");


            var borrow = _service.Get(BorrowId, BorrowDetailId);
            if(borrow == null)
            {
                return NotFound();
            }
           
            return View("Edit", borrow);
        }

        [HttpPost]
        public IActionResult Update(Borrow borrow, BorrowDetail borrowDetail)
        {
            if (!ModelState.IsValid)
            {
                return View("Edit");
            }
            var result = _service.Updade(borrow, borrowDetail);
            if (result)
            {
                return RedirectToAction("Index", "BorrowDetial");
            }

            return View("Edit");
        }

        [HttpGet]
        public IActionResult Delete(int BorrowId, int BorrowDetailId)
        {

            var customer = _cus.GetAll();
            ViewBag.Customer = new SelectList(customer, "CustomerId", "CustomerName");
            //---------------------------------------------------------------------//

            var librarian = _lia.GetAll();
            ViewBag.librarians = new SelectList(librarian, "LibrarianId", "LibrarianName");
            //-------------------------------------------------------------------------//

            var book = _book.GetAll();
            ViewBag.Book = new SelectList(book, "BookId", "Catalog.CatalogName");

            var borrow = _service.Get(BorrowId, BorrowDetailId);
            if (borrow == null)
            {
                return NotFound();
            }

            return View("Delete",borrow);
        }

        [HttpPost]
        public IActionResult Destroy(int BorrowId, int BorrowDetailId)
        {
            if (!ModelState.IsValid)
            {
                return View("Delete");
            }
            var result = _service.Delete(BorrowId, BorrowDetailId);
            if (result != null)
            {
                return RedirectToAction("Index", "BorrowDetial");
            }
            return View("Delete");
        }
    }
}

Library/Views/Borrow/Create.cshtml
@model Library.Models.BorrowandBorrowDetail
@{
    ViewData["Title"] = "Add New Borrow";
}
<div class="card">
    <div class="card-header">
        <h4 class="title">Add Borrow</h4>
    </div>
    <div class="card-body">
        <form asp-action="Store" asp-controller="Borrow" method="post">
            <div class="row">
                <div class="form-group col-sm-6">
                    <label asp-for="Borrow.CustomerId" class="control-label">Customer Name</label>
                    <select asp-for="Borrow.CustomerId" class="custom-select"
                            asp-items="@ViewBag.Customer">
                        <option> Please Select Customer Name</option>

                    </select>
                </div>
                <div class="form-group col-sm-6">
                    <label asp-for="Borrow.LibrarianId" class="control-label">Librarian Name</label>
                    <select asp-for="Borrow.LibrarianId" class="custom-select"
                            asp-items="@ViewBag.librarians">
                        <option> Please Select Librarian Name</option>
                    </select>
                </div>

            </div>
            <div class="row">
                <div class="form-group col-sm-6">
                    <label asp-for="Borrow.BorrowDate" class="control-label">BorrowDate</label>
                    <input type="date" placeholder="BorrowDate" asp-for="Borrow.BorrowDate" class="form-control" />
                </div>
                <div class="form-group col-sm-6">
                    <label asp-for="Borrow.Duedate" class="control-label">DueDate</label>
                    <input type="date" placeholder="DueDate" asp-for="Borrow.Duedate" class="form-control" />
                </div>


            </div>

            <div class="row">

                <div class="form-group col-sm-6">
                    <label asp-for="Borrow.BorrowCode" class="control-label"> BorrowCode</label>
                    <input type="text" placeholder="BorrowCode" asp-for="Borrow.BorrowCode" class="form-control" />
                </div>
                <div class="form-group col-sm-6">
                    <label asp-for="Borrow.Memo" class="control-label"> Memo</label>
                    <input type="text" asp-for="Borrow.Memo" placeholder="Memo" class="form-control" />
                </div>
            </div>
            <div class="row">
                <div class="form-group col-sm-6">
                    <label asp-for="Borrow.Depositamount" class="control-label">Depositamount</label>
                    <input type="text" placeholder="DespositamountOB" asp-for="Borrow.Depositamount" class="form-control" />
                </div>
                <div class="form-group col-sm-6 ">
                    <label asp-for="Borrow.FineAmount" class="control-label">FineAmount</label>
                    <input class="form-control" placeholder="Fine Amount" type="text" asp-for="Borrow.FineAmount" />

                </div>

            </div>
            <div class="form-group form-check">

                <input type="checkbox" asp-for="Borrow.IsHidden" class="form-check-input" />
                <label asp-for="Borrow.IsHidden" class="form-check-label ml-1"> IsHidden</label>
            </div>


            
                <div class="card-header">
                    <h4 class="title">BorrowDetail</h4>
                </div>
                <div class="row">
                    <input asp-for="BorrowDetail.BorrowId" type="hidden" />
                    <div class="form-group col-sm-6">
                        <label asp-for="BorrowDetail.BookId" class="control-label">Book Name</label>
                        <select asp-for="BorrowDetail.BookId"  asp-items="@ViewBag.Book" class="custom-select">
                            <option> Please Select Book Name</option>
                        </select>

                    </div>

                    <div class="form-group col-sm-6">
                        <label asp-for="BorrowDetail.Note" class="control-label">Note</label>
                        <input asp-for="BorrowDetail.Note" placeholder="Note" class="form-control" />

                    </div>

                </div>
                <div class="form-group">
                    <label asp-for="BorrowDetail.ReturnDate" class="control-label"> ReturnDate</label>
                    <input asp-for="BorrowDetail.ReturnDate" type="date" class="form-control" />
                </div>
                <div class="form-group fomr-check">
                    <input asp-for="BorrowDetail.IsReturn" class="form-check-input" />
                    <label asp-for="BorrowDetail.IsReturn" class="form-check-label">IsReturn</label>
                </div>
            



            <div class="form-group">
                <button type="submit" class="btn btn-success btn-sm float-lg-right ml-2">Add Borrow</button>
                <a asp-action="Index" asp-controller="Borrowdeatil" class="btn btn-danger btn-sm float-lg-right">Cancel</a>
            </div>
        </form>
    </div>
</div>

Library/Views/Borrow/Delete.cshtml
@model Library.Models.BorrowandBorrowDetail
@{
    ViewData["Title"] = "Delete Borrow";
}
<div class="card">
    <div class="card-header">
        <h4 class="title">Delete Borrow</h4>
    </div>
    <div class="card-body">
        <form asp-action="Destroy" asp-controller="Borrow" method="post">
            <input asp-for="BorrowDetail.BorrowId" type="hidden" />
            <input asp-for="Borrow.BorrowId" type="hidden" />
            <div class="row">
                <div class="form-group col-sm-6">
                    <label asp-for="Borrow.CustomerId" class="control-label">Customer Name</label>
                    <select asp-for="Borrow.CustomerId" class="custom-select"
                            asp-items="@ViewBag.Customer">
                        <option> Please Select Customer Name</option>

                    </select>
                </div>
                <div class="form-group col-sm-6">
                    <label asp-for="Borrow.LibrarianId" class="control-label">Librarian Name</label>
                    <select asp-for="Borrow.LibrarianId" class="custom-select"
                            asp-items="@ViewBag.librarians">
                        <option> Please Select Librarian Name</option>
                    </select>
                </div>
            </div>

            <div class="row">
                <div class="form-group col-sm-6">
                    <label asp-for="Borrow.BorrowDate" class="control-label">BorrowDate</label>
                    <input type="date" placeholder="BorrowDate" asp-for="Borrow.BorrowDate" class="form-control" />
                </div>
                <div class="form-group col-sm-6">
                    <label asp-for="Borrow.Duedate" class="control-label">DueDate</label>
                    <input type="date" placeholder="DueDate" asp-for="Borrow.Duedate" class="form-control" />
                </div>

            </div>

            <div class="row">

                <div class="form-group col-sm-6">
                    <label asp-for="Borrow.BorrowCode" class="control-label"> BorrowCode</label>
                    <input type="text" placeholder="BorrowCode" asp-for="Borrow.BorrowCode" class="form-control" />
                </div>
                <div class="form-group col-sm-6">
                    <label asp-for="Borrow.Memo" class="control-label"> Memo</label>
                    <input type="text" asp-for="Borrow.Memo" placeholder="Memo" class="form-control" />
                </div>
            </div>
            <div class="row">
                <div class="form-group col-sm-6">
                    <label asp-for="Borrow.Depositamount" class="control-label">Depositamount</label>
                    <input type="text" placeholder="DespositamountOB" asp-for="Borrow.Depositamount" class="form-control" />
                </div>
                <div class="form-group col-sm-6 ">
                    <label asp-for="Borrow.FineAmount" class="control-label">FineAmount</label>
                    <input class="form-control" placeholder="Fine Amount" type="text" asp-for="Borrow.FineAmount" />

                </div>

            </div>
            <div class="form-group form-check">

                <input type="checkbox" asp-for="Borrow.IsHidden" class="form-check-input" />
                <label asp-for="Borrow.IsHidden" class="form-check-label ml-1"> IsHidden</label>
            </div>



            <div class="card-header">
                <h4 class="title">BorrowDetail</h4>
            </div>
            <input asp-for="BorrowDetail.BorrowDetailId" type="hidden" />
            <div class="row">
               
                <div class="form-group col-sm-6">
                    <label asp-for="BorrowDetail.BookId" class="control-label">Book Name</label>
                    <select asp-for="BorrowDetail.BookId" asp-items="@ViewBag.Book" class="custom-select">
                        <option> Please Select Book Name</option>
                    </select>

                </div>

                <div class="form-group col-sm-6">
                    <label asp-for="BorrowDetail.Note" class="control-label">Note</label>
                    <input asp-for="BorrowDetail.Note" placeholder="Note" class="form-control" />

                </div>

            </div>
            <div class="form-group">
                <label asp-for="BorrowDetail.ReturnDate" class="control-label"> ReturnDate</label>
                <input asp-for="BorrowDetail.ReturnDate" type="date" class="form-control" />
            </div>
            <div class="form-group fomr-check">
                <input asp-for="BorrowDetail.IsReturn" class="form-check-input" />
                <label asp-for="BorrowDetail.IsReturn" class="form-check-label">IsReturn</label>
            </div>




            <div class="form-group">
                <button type="submit" class="btn btn-success btn-sm float-lg-right ml-2">Delete Borrow</button>
                <a asp-action="Index" class="btn btn-danger btn-sm float-lg-right">Cancel</a>
            </div>
        </form>
    </div>
</div>

Library/Views/Borrow/Edit.cshtml
@model Library.Models.BorrowandBorrowDetail
@{
    ViewData["Title"] = "Borrow And BorrowDeatil";
}
<div class="card">
    <div class="card-header">
        <h4 class="title">Update Borrow</h4>
    </div>
    <div class="card-body">
        <form asp-action="Update" asp-controller="Borrow" method="post">
            <input asp-for="Borrow.BorrowId" type="hidden" />
            <div class="row">
                <div class="form-group col-sm-6">
                    <label asp-for="Borrow.CustomerId" class="control-label">Customer Name</label>
                    <select asp-for="Borrow.CustomerId" class="custom-select"
                            asp-items="@ViewBag.Customer">
                        <option> Please Select Customer Name</option>

                    </select>
                </div>
                <div class="form-group col-sm-6">
                    <label asp-for="Borrow.LibrarianId" class="control-label">Librarian Name</label>
                    <select asp-for="Borrow.LibrarianId" class="custom-select"
                            asp-items="@ViewBag.librarians">
                        <option> Please Select Librarian Name</option>
                    </select>
                </div>
            </div>

            <div class="row">
                <div class="form-group col-sm-6">
                    <label asp-for="Borrow.BorrowDate" class="control-label">BorrowDate</label>
                    <input type="date" placeholder="BorrowDate" asp-for="Borrow.BorrowDate" class="form-control" />
                </div>
                <div class="form-group col-sm-6">
                    <label asp-for="Borrow.Duedate" class="control-label">DueDate</label>
                    <input type="date" placeholder="DueDate" asp-for="Borrow.Duedate" class="form-control" />
                </div>


            </div>

            <div class="row">

                <div class="form-group col-sm-6">
                    <label asp-for="Borrow.BorrowCode" class="control-label"> BorrowCode</label>
                    <input type="text" placeholder="BorrowCode" asp-for="Borrow.BorrowCode" class="form-control" />
                </div>
                <div class="form-group col-sm-6">
                    <label asp-for="Borrow.Memo" class="control-label"> Memo</label>
                    <input type="text" asp-for="Borrow.Memo" placeholder="Memo" class="form-control" />
                </div>
            </div>
            <div class="row">
                <div class="form-group col-sm-6">
                    <label asp-for="Borrow.Depositamount" class="control-label">Depositamount</label>
                    <input type="text" placeholder="DespositamountOB" asp-for="Borrow.Depositamount" class="form-control" />
                </div>
                <div class="form-group col-sm-6 ">
                    <label asp-for="Borrow.FineAmount" class="control-label">FineAmount</label>
                    <input class="form-control" placeholder="Fine Amount" type="text" asp-for="Borrow.FineAmount" />

                </div>

            </div>
            <div class="form-group form-check">

                <input type="checkbox" asp-for="Borrow.IsHidden" class="form-check-input" />
                <label asp-for="Borrow.IsHidden" class="form-check-label ml-1"> IsHidden</label>
            </div>



            <div class="card-header">
                <h4 class="title">BorrowDetail</h4>
            </div>
            <input asp-for="BorrowDetail.BorrowDetailId" type="hidden" />
            <div class="row">
                <input asp-for="BorrowDetail.BorrowId" type="hidden" />
                <div class="form-group col-sm-6">
                    <label asp-for="BorrowDetail.BookId" class="control-label">Book Name</label>
                    <select asp-for="BorrowDetail.BookId" asp-items="@ViewBag.Book" class="custom-select">
                        <option> Please Select Book Name</option>
                    </select>

                </div>

                <div class="form-group col-sm-6">
                    <label asp-for="BorrowDetail.Note" class="control-label">Note</label>
                    <input asp-for="BorrowDetail.Note" placeholder="Note" class="form-control" />

                </div>

            </div>
            <div class="form-group">
                <label asp-for="BorrowDetail.ReturnDate" class="control-label"> ReturnDate</label>
                <input asp-for="BorrowDetail.ReturnDate" type="date" class="form-control" />
            </div>
            <div class="form-group fomr-check">
                <input asp-for="BorrowDetail.IsReturn" class="form-check-input" />
                <label asp-for="BorrowDetail.IsReturn" class="form-check-label">IsReturn</label>
            </div>

            <div class="form-group">
                <button type="submit" class="btn btn-success btn-sm float-lg-right ml-2">Update Borrow</button>
                <a asp-action="Index" class="btn btn-danger btn-sm float-lg-right">Cancel</a>
            </div>
        </form>
    </div>
</div>