Library/Controllers/AppUserController.cs
using Library.Models;
using Library.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Library.Controllers
{
	public class AppUserController : Controller
	{
		private readonly IAppUserService _service;

		public AppUserController(IAppUserService service)
		{
			_service = service;

		}

		[Authorize(Roles = "Admin")]
		public IActionResult Index()
        {
            var appuser = _service.GetAll();

            return View("Index", appuser);
        }

        [HttpGet]
		public IActionResult Create()
		{
			return View();
		}

		[HttpPost]
		public IActionResult Store(AppUser appUser)
		{
			if (!ModelState.IsValid)
			{
				return View(appUser);
			}
			var result = _service.Create(appUser);
			if (result)
			{
				TempData["ToastrMessage"] = "User Has ben Added SuccessFully";
                TempData["ToastrMessageType"] = "success";
                return RedirectToAction("Index");
			}
            TempData["ToastrMessage"] = "Can't Create User";
            TempData["ToastrMessageType"] = "error";
            return View(appUser);
		}
		[HttpGet]
		public IActionResult Edit(int AppUserId)
		{
			var result = _service.Get(AppUserId);
			return View("Edit", result);
		}
        [HttpPost]
        public IActionResult Update(AppUser appUser)
        {
            if (!ModelState.IsValid)
            {
                return View(appUser);
            }

            var result = _service.Update(appUser);
            if (result)
            {
                TempData["ToastrMessage"] = "User has been updated successfully!";
                TempData["ToastrMessageType"] = "success";
                return RedirectToAction("Index");
            }

            TempData["ToastrMessage"] = "Failed to update user!";
            TempData["ToastrMessageType"] = "error";
            return View(appUser);
        }



        [HttpGet]
		public IActionResult Delete(int AppUserId)
		{
			var result = _service.Get(AppUserId);
			return View("Delete", result);
		}
		[HttpPost]
		public IActionResult Destroy(int appUserId)
		{
			if (!ModelState.IsValid)
			{
				return View(appUserId);
			}
			var result = _service.Delete(appUserId);
			if (result)
			{
               
                return RedirectToAction("Index");
			}
			return View(appUserId);
		}
	}
}

Library/Controllers/BookController.cs
using Library.Models;
using Library.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Library.Controllers
{
    public class BookController : Controller
    {
        private readonly ICatalogService _catalogService;
        private readonly IBookService _serive;
        private readonly IBorrowDetailService _detail;
        public BookController(IBookService serive, ICatalogService catalogService, IBorrowDetailService detail)
        {
            _serive = serive;
            _catalogService = catalogService;
            _detail = detail;
        }


        public IActionResult Index(int? page, string searchTerm)
        {
            int pageNumber = page ?? 1; // If no page number is provided, default to page 1
            int pageSize = 10; // Number of books per page

            // Get the total count of books
            var totalCount = _serive.GetAll().Count();

            // Calculate the number of items to skip
            int skip = (pageNumber - 1) * pageSize;

            // Get the paginated list of books
            var books = _serive.GetAll().Skip(skip).Take(pageSize).ToList();

            var borrowDetails = _detail.GetAll(searchTerm);

            // Use SelectMany to flatten the list of BookIds
            var selectedBookCodes = borrowDetails.SelectMany(bd => new[] { bd.BookId }).ToList();

            // Pass the paginated list of books and total count to the view

            ViewBag.TotalCount = totalCount;
            ViewBag.PageNumber = pageNumber;
            ViewBag.PageSize = pageSize;
            ViewBag.SelectedBookCodes = selectedBookCodes;


            return View(books);
        }

        [HttpGet]
        public IActionResult Create()
        {
            var catalog = _catalogService.GetAll();
            ViewBag.catalogs = new SelectList(catalog, "CatalogId", "CatalogName");
            return View("Create");
        }


        [HttpPost]
        public IActionResult Store(Book book)
        {
            if (ModelState.IsValid)
            {
                bool bookCodeExists = _serive.BookCodeExists(book.BookCode);
                if (bookCodeExists)
                {
                    ModelState.AddModelError(nameof(book.BookCode), "The BookCode already exists...!");
                    return View("Create", book);
                }

                bool success = _serive.Create(book);
                if (success)
                {
                    TempData["ToastrMessage"] = "Create SuccessFully";
                    TempData["ToastrMessageType"] = "success";
                    return RedirectToAction("Index");
                }
            }
            return View("Create", book);
        }
        [HttpGet]
        public IActionResult Edit(int BookId)
        {
            var catalog = _catalogService.GetAll();
            ViewBag.catalogs = new SelectList(catalog, "CatalogId", "CatalogName");

            var book = _serive.Get(BookId);
            return View("Edit", book);
        }
        [HttpPost]
        public IActionResult Update(Book book)
        {
            if (!ModelState.IsValid)
            {
                return View(book);
            }
            var result = _serive.Update(book);
            if (result)
            {
                TempData["ToastrMessage"] = "Update SuccessFully";
                TempData["ToastrMessageType"] = "success";
                return RedirectToAction("Index");
            }
            return View(book);
        }

        [HttpGet]
        public IActionResult Delete(int BookId)
        {
            var book = _serive.Get(BookId);
            return View("Delete", book);
        }
        [HttpPost]
        public IActionResult Destroy(int bookId)
        {
            if (!ModelState.IsValid)
            {
                return View(bookId);
            }
            var result = _serive.Delete(bookId);
            if (result)
            {
                return RedirectToAction("Index");
            }
            return View(bookId);
        }

    }
}

Library/Controllers/RoleController.cs
using Library.Models;
using Library.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Library.Controllers
{
    public class RoleController : Controller
    {
        private readonly IRoleService _service;
        private readonly IAppUserService _user;
        private readonly IHttpContextAccessor _context;
        public RoleController(IRoleService service, IAppUserService user, IHttpContextAccessor context)
        {
            _service = service;
            _user = user;
            _context = context;
        }

        public IActionResult Index()
        {
            var roles = _service.GetAllRoles();
            return View("Index",roles);
        }

        [HttpGet]
        public IActionResult Create()
        {
            var user = _user.GetAll();

            ViewBag.User = new SelectList(user, "AppUserId", "UserName");
            return View();
        }
        [HttpPost]
        public IActionResult Store(Role role)
        {
            if(!ModelState.IsValid)
            {
                return View("Create", role);
            }
            var result = _service.CreateRole(role);
            if(result)
            {
                return RedirectToAction("Index");
            }
            return View("Create", role);
        }

        [HttpGet]
        public IActionResult Edit(int RoleId)
        {
            var user = _user.GetAll();
            ViewBag.User = new SelectList(user, "AppUserId", "UserName");

            var role = _service.GetRole(RoleId);
            return View("Edit", role);
        }
        [HttpPost]
        public IActionResult Update(Role role)
        {
            if (!ModelState.IsValid)
            {
                return View("Edit", role);
                
            }
            var result = _service.UpdateRole(role);
            if(result)
            {
                return RedirectToAction("Index");
            }
            return View("Edit", role);
        }

        [HttpGet]
        public IActionResult Delete(int RoleId)
        {
            var user = _user.GetAll();
            ViewBag.User = new SelectList(user, "AppUserId", "UserName");

            var role = _service.GetRole(RoleId);
            return View("Delete", role);
        }
        [HttpPost]
        public IActionResult Destroy(int RoleId)
        {
            if (!ModelState.IsValid)
            {
                return View("Delete", RoleId);
            }
            var result = _service.DeleteRole(RoleId);
            if(result)
            {
                return RedirectToAction("Index");
            }
            return View("Delete", RoleId);
        }

        

    }
}

Library/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <partial name="_csslink" />


</head>
<body>

    <div id="main-wrapper">
        <!--**********************************
            Nav header start
        ***********************************-->
        <div class="nav-header">
            <div class="brand-logo">
                <a href="#">
                    <b class="logo-abbr">
                        <img src="~/quixlab-bootstrap-main/quixlab-bootstrap-main/theme/images/l.png" />
                    </b>
                    <span class="logo-compact">
                        <img src="~/quixlab-bootstrap-main/quixlab-bootstrap-main/theme/images/l.png" />
                    </span>
                    <span class="brand-title">
                       
                        <img src="~/quixlab-bootstrap-main/quixlab-bootstrap-main/theme/images/libary.png" />
                    </span>
                </a>
            </div>
        </div>

        <partial name="_navigationbar" />
        <partial name="_sidebar" />

        <div class="content-body">
            <div class="container-fluid mt-3">
                @RenderBody()
            </div>
        </div>
    </div>

    <partial name="_scip" />

    @RenderSection("Scripts", required: false)
</body>
</html>

<script>
    $(document).ready(function () {
    @if (TempData["ToastrMessage"] != null && TempData["ToastrMessageType"] != null)
    {
        <text>
                                var messageType = '@TempData["ToastrMessageType"]';
            var message = '@TempData["ToastrMessage"]';
            toastr.options = {
                "closeButton": true,
                "progressBar": true,
                "positionClass": "toast-top-right",
                "timeOut": "5000"
            };
            toastr[messageType](message);
        </text>
    }
            });
</script>

@section Scripts {
    <script>
        function confirmDelete() {
            swal({
                title: "Are you sure?",
                text: "Do you really want to delete this user?",
                icon: "warning",
                buttons: {
                    cancel: "No, keep it",
                    confirm: {
                        text: "Yes, delete it",
                        value: true,
                        visible: true,
                        className: "btn-danger",
                        closeModal: true
                    }
                },
                dangerMode: true,
            }).then((willDelete) => {
                if (willDelete) {
                    $('#deleteForm').submit();
                } else {
                    swal("Your user is safe!", {
                        icon: "info",
                    });
                }
            });
        }
    </script>
}

Library/Views/Shared/_Login.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="icon" type="image/png" sizes="16x16" href="../../assets/images/favicon.png">
    <link href="~/quixlab-bootstrap-main/quixlab-bootstrap-main/theme/icons/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
     
    <link href="~/quixlab-bootstrap-main/quixlab-bootstrap-main/theme/css/style.css" rel="stylesheet" />
</head>

<body class="h-100">

    @RenderBody()



    <script src="~/jquery/jquery.min.js"></script>
    <script src="~/jquery-validate/jquery.validate.min.js"></script>
    <script src="~/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>

    <script src="~/quixlab-bootstrap-main/quixlab-bootstrap-main/theme/plugins/common/common.min.js"></script>
    
    <script src="~/quixlab-bootstrap-main/quixlab-bootstrap-main/theme/js/custom.min.js"></script>
    <script src="~/quixlab-bootstrap-main/quixlab-bootstrap-main/theme/js/settings.js"></script>
    <script src="~/quixlab-bootstrap-main/quixlab-bootstrap-main/theme/js/gleek.js"></script>
    <script src="~/quixlab-bootstrap-main/quixlab-bootstrap-main/theme/js/styleswitcher.js"></script>
    <script src="~/quixlab-bootstrap-main/quixlab-bootstrap-main/theme/plugins/jquery-validation/jquery.validate.min.js"></script>

</body>
</html>

Library/Views/Shared/_csslink.cshtml
<link href="~/quixlab/css/style.css" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
<link href="~/quixlab-bootstrap-main/quixlab-bootstrap-main/theme/plugins/toastr/css/toastr.min.css" rel="stylesheet" />
<link href="~/quixlab-bootstrap-main/quixlab-bootstrap-main/theme/css/style.css" rel="stylesheet" />
<!-- DataTables CSS -->
<link href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css" rel="stylesheet">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.0/css/bootstrap.min.css" />

<link href="~/plugins/pg-calendar/css/pignose.calendar.min.css" rel="stylesheet">

<link rel="stylesheet" href="./plugins/chartist/css/chartist.min.css">

<link rel="stylesheet" href="./plugins/chartist-plugin-tooltips/css/chartist-plugin-tooltip.css">
<link href="~/quixlab-bootstrap-main/quixlab-bootstrap-main/theme/plugins/quill/css/quill.core.css" rel="stylesheet" />
<link href="~/quixlab-bootstrap-main/quixlab-bootstrap-main/theme/plugins/quill/css/quill.snow.css" rel="stylesheet" />
<link href="~/quixlab-bootstrap-main/quixlab-bootstrap-main/theme/plugins/owl.carousel/dist/css/owl.theme.default.min.css" rel="stylesheet" />
<link href="~/quixlab-bootstrap-main/quixlab-bootstrap-main/theme/plugins/bootstrap-colorpicker/css/bootstrap-colorpicker.min.css" rel="stylesheet" />
<link href="~/quixlab-bootstrap-main/quixlab-bootstrap-main/theme/css/style.css" rel="stylesheet" />
<link href="~/quixlab-bootstrap-main/quixlab-bootstrap-main/theme/plugins/chartist-plugin-tooltips/css/chartist-plugin-tooltip.css" rel="stylesheet" />
<link href="~/quixlab-bootstrap-main/quixlab-bootstrap-main/theme/plugins/chartist/css/chartist.min.css" rel="stylesheet" />
<link href="~/quixlab-bootstrap-main/quixlab-bootstrap-main/theme/plugins/pg-calendar/css/pignose.calendar.min.css" rel="stylesheet" />
<link rel="stylesheet" href="https://unpkg.com/ionicons@5.5.2/dist/css/ionicons.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
<link rel="stylesheet" href="https://unpkg.com/coreui/icons/css/free.min.css">
<link rel="stylesheet" href="https://unpkg.com/coreui/icons/css/brand.min.css">
<link rel="stylesheet" href="https://unpkg.com/coreui/icons/css/flag.min.css">
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" rel="stylesheet" />
<link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" rel="stylesheet">
<link href="~/quixlab-bootstrap-main/quixlab-bootstrap-main/theme/plugins/datatables.net-bs4/css/datatables.bootstrap4.min.css" rel="stylesheet" />
<link href="~/quixlab-bootstrap-main/quixlab-bootstrap-main/theme/plugins/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css" rel="stylesheet" />
<link href="~/quixlab-bootstrap-main/quixlab-bootstrap-main/theme/plugins/select2/css/select2.min.css" rel="stylesheet" />
<style>
    .nav-header {
        display: flex;
        align-items: center;
        background-color: #ffffff; /* White background */
        padding: 10px;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1); /* Optional: Adds a subtle shadow for depth */
    }

    .brand-logo {
        display: flex;
        align-items: center;
    }

        .brand-logo a {
            display: flex;
            align-items: center;
            text-decoration: none;
        }

        .brand-logo img {
            height: 40px;
        }

    .nav-title {
        font-size: 24px;
        font-weight: bold;
        color: #333;
        margin-left: 10px;
    }
</style>

Library/Views/Shared/_navigationbar.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor _context

<div class="header">
    <div class="header-content clearfix">
        <div class="nav-control">
            <div class="hamburger">
                <span class="toggle-icon"><i class="icon-menu"></i></span>
            </div>
        </div>
        <div class="header-right">
            <ul class="clearfix">

                <li class="icons dropdown d-none d-md-flex">
                    <a href="javascript:void(0)" class="log-user" data-toggle="dropdown">
                        <span>English</span>  <i class="fa fa-angle-down f-s-14" aria-hidden="true"></i>
                    </a>
                    <div class="drop-down dropdown-language animated fadeIn  dropdown-menu">
                        <div class="dropdown-content-body">
                            <ul>
                                <li><a href="javascript:void()">English</a></li>
                                <li><a href="javascript:void()">Dutch</a></li>
                            </ul>
                        </div>
                    </div>
                </li>
                <li class="icons dropdown">
                    <div class="user-img c-pointer position-relative" data-toggle="dropdown">
                        <span class="activity active"></span>

                        <img src="~/quixlab-bootstrap-main/quixlab-bootstrap-main/theme/images/avatar/11.png" height="40" width="40" alt="">
                    </div>
                    <div class="drop-down dropdown-profile animated fadeIn dropdown-menu">
                        <div class="dropdown-content-body">
                            <ul>
                                @if (_context.HttpContext.Session.GetString("AppUserId") != null)
                                {
                                    <li>
                                        <p class="ml-4">
                                              Hello  @_context.HttpContext.Session.GetString("UserName")
                                        </p>

                                    </li>
                                }
                                <hr class="my-1">
                                <li>
                                    <form asp-controller="Account" asp-action="LogOut" method="post" style="display: inline-block;">
                                        @Html.AntiForgeryToken()
                                        <button type="submit" class="btn btn-outline-light ml-4" style="border: none; width:100%;">
                                            Sign Out
                                        </button>
                                    </form>
                                </li>
                            </ul>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</div>

Library/Views/Shared/_scip.cshtml
<!-- jQuery -->
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>


<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<!-- jQuery -->
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>

<!-- DataTables JS -->
<script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>

<!-- QuixLab JS -->
<script src="~/quixlab/js/scripts.js"></script>

<script src="~/quixlab-bootstrap-main/quixlab-bootstrap-main/theme/plugins/jquery/jquery.min.js"></script>
<!-- jQuery Validation -->
<script src="~/jquery-validation/jquery.validate.min.js"></script>
<script src="~/quixlab-bootstrap-main/quixlab-bootstrap-main/theme/plugins/jquery-validation/jquery.validate.min.js"></script>
<script src="~/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
<!-- Toastr -->
<script src="~/bootstrap-toaster/js/bootstrap-toaster.min.js"></script>
<script src="~/quixlab-bootstrap-main/quixlab-bootstrap-main/theme/plugins/toastr/js/toastr.min.js"></script>
<script src="~/quixlab-bootstrap-main/quixlab-bootstrap-main/theme/plugins/toastr/js/toastr.init.js"></script>
<!-- Common and Custom Scripts -->
<script src="~/quixlab-bootstrap-main/quixlab-bootstrap-main/theme/plugins/common/common.min.js"></script>
<script src="~/quixlab-bootstrap-main/quixlab-bootstrap-main/theme/js/custom.min.js"></script>
<script src="~/quixlab-bootstrap-main/quixlab-bootstrap-main/theme/js/settings.js"></script>
<script src="~/quixlab-bootstrap-main/quixlab-bootstrap-main/theme/js/gleek.js"></script>
<script src="~/quixlab-bootstrap-main/quixlab-bootstrap-main/theme/js/styleswitcher.js"></script>
<!-- SweetAlert2 -->
<script src="~/quixlab-bootstrap-main/quixlab-bootstrap-main/theme/plugins/sweetalert2/dist/sweetalert2.min.js"></script>
<!-- Additional Plugins -->
<script src="~/quixlab-bootstrap-main/quixlab-bootstrap-main/theme/plugins/chart.js/chart.bundle.min.js"></script>
<script src="~/quixlab-bootstrap-main/quixlab-bootstrap-main/theme/plugins/circle-progress/circle-progress.min.js"></script>
<script src="~/quixlab-bootstrap-main/quixlab-bootstrap-main/theme/plugins/d3v3/index.js"></script>
<script src="~/quixlab-bootstrap-main/quixlab-bootstrap-main/theme/plugins/topojson/topojson.min.js"></script>
<script src="~/quixlab-bootstrap-main/quixlab-bootstrap-main/theme/plugins/datamaps/datamaps.dma.min.js"></script>
<script src="~/quixlab-bootstrap-main/quixlab-bootstrap-main/theme/plugins/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js"></script>
<script src="~/quixlab-bootstrap-main/quixlab-bootstrap-main/theme/plugins/raphael/raphael.min.js"></script>
<script src="~/quixlab-bootstrap-main/quixlab-bootstrap-main/theme/plugins/morris/morris.min.js"></script>
<script src="~/quixlab-bootstrap-main/quixlab-bootstrap-main/theme/plugins/moment/moment.min.js"></script>
<script src="~/quixlab-bootstrap-main/quixlab-bootstrap-main/theme/plugins/pg-calendar/js/pignose.calendar.min.js"></script>
<script src="~/quixlab-bootstrap-main/quixlab-bootstrap-main/theme/plugins/chartist/js/chartist.min.js"></script>
<script src="~/quixlab-bootstrap-main/quixlab-bootstrap-main/theme/plugins/chartist-plugin-tooltips/js/chartist-plugin-tooltip.min.js"></script>
<script src="~/quixlab-bootstrap-main/quixlab-bootstrap-main/theme/plugins/bootstrap-menu/bootstrapmenu.min.js"></script>
<script src="~/quixlab-bootstrap-main/quixlab-bootstrap-main/theme/plugins/amcharts/plugins/dataloader.min.js"></script>
<script src="~/quixlab-bootstrap-main/quixlab-bootstrap-main/theme/plugins/quill/js/quill.js"></script>
<script src="~/quixlab-bootstrap-main/quixlab-bootstrap-main/theme/plugins/preview/plugin.js"></script>
<script src="~/quixlab-bootstrap-main/quixlab-bootstrap-main/theme/plugins/peity/jquery.peity.min.js"></script>
<script src="~/quixlab-bootstrap-main/quixlab-bootstrap-main/theme/plugins/pastefromword/filter/default.js"></script>
<script src="~/quixlab-bootstrap-main/quixlab-bootstrap-main/theme/plugins/bootstrap-colorpicker/js/bootstrap-colorpicker.min.js"></script>
<script src="~/quixlab-bootstrap-main/quixlab-bootstrap-main/theme/plugins/owl.carousel/dist/js/owl.carousel.min.js"></script>
<script src="scripts.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script type="module" src="https://cdn.jsdelivr.net/npm/ionicons@latest/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://cdn.jsdelivr.net/npm/ionicons@latest/dist/ionicons/ionicons.js"></script>
<script src="~/quixlab-bootstrap-main/quixlab-bootstrap-main/theme/js/dashboard/dashboard-1.js"></script>
<script src="~/jqplugin/jquery.jqplugin.min.js"></script>

<script src="~/quixlab-bootstrap-main/quixlab-bootstrap-main/theme/plugins/jquery/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="~/quixlab-bootstrap-main/quixlab-bootstrap-main/theme/plugins/selectall/plugin.js"></script>
<script src="~/quixlab-bootstrap-main/quixlab-bootstrap-main/theme/plugins/select2/js/select2.full.min.js"></script>

Library/Views/Shared/_sidebar.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor _contex
@{
    var roles = _contex.HttpContext.Session.GetString("roles")?.Split(',') ?? new string[0];
    var IsAdmin = roles.Contains("Admin");
    var IsStaff = roles.Contains("Staff");
    var IsUser = roles.Contains("User");
}

<div class="nk-sidebar">
   <div class="nk-nav-scroll">
        <ul class="metismenu in" id="menu">

            <li>
                <a asp-controller="Home" asp-action="Index" aria-expanded="false">
                    <ion-icon name="home"></ion-icon>
                    <span class="nav-text ml-1">Home</span>
                </a>
            </li>
            @if (IsAdmin || IsStaff)
            {
                <li>
                    <a asp-controller="Librarian" asp-action="Index" aria-expanded="false">
                        <ion-icon name="person"></ion-icon>
                        <span class="nav-text ml-1">Librian</span>
                    </a>
                </li>
            }
            @if (IsAdmin || IsStaff || IsUser)
            {
                <li class="mega-menu mega-menu-sm">
                    <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                        <ion-icon name="people"></ion-icon>
                        <span class="nav-text ml-1"> Customer</span>
                    </a>
                    <ul aria-expanded="false" class="collapse">
                        <li>

                            <a asp-controller="Customer" asp-action="Index">
                                <ion-icon name="person-add"></ion-icon>
                                <span class="nav-text ml-1"> Customer</span>
                            </a>
                        </li>
                        <li>
                            <a asp-controller="CustomerType" asp-action="Index">
                                <ion-icon name="person"></ion-icon>
                                <span class="nav-text ml-1"> CustomerType</span>
                            </a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a asp-controller="Catalog" asp-action="Index">
                        <ion-icon name="pricetags"></ion-icon>
                        <span class="nav-text ml-1">Catalog</span>
                    </a>
                </li>
                <li>
                    <a asp-controller="Book" asp-action="Index">
                        <ion-icon name="book"></ion-icon>
                        <span class="nav-text ml-1">Book</span>
                    </a>
                </li>
                <li>
                    <a asp-controller="BorrowDetial" asp-action="Index" aria-expanded="false">
                        <ion-icon name="wallet"></ion-icon>
                        <span class="nav-text ml-1">Borrow</span>
                    </a>
                </li>
            }

           

            @if (IsAdmin)
            {
                <li class="nav-label">User Manager</li>
                <li>
                    <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                        <ion-icon name="person"></ion-icon>
                        <span class="nav-text ml-2">App User</span>
                    </a>
                    <ul aria-expanded="false" class="collapse">
                        <li>
                            <a asp-controller="AppUser" asp-action="Index">
                                User
                            </a>
                        </li>
                        <li>
                            <a asp-controller="Role" asp-action="Index">User Role</a>
                        </li>
                        <li>
                            <a asp-controller="AppUserPermission" asp-action="Index">UserPermission</a>
                        </li>

                    </ul>
                </li>
            }
        </ul>
   </div>
</div>
<script>
    $(document).ready(function () {
        $('.has-arrow').on('click', function () {
            $(this).next('.collapse').slideToggle();
            $(this).parent().toggleClass('open');
        });
    });

</script>